services:
  postgres:
    image: postgres:16.4
    container_name: koryto_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pswd
      POSTGRES_DB: koryto
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.7
               -c wal_buffers=16MB
               -c default_statistics_target=100
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d koryto" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true
  web:
    env_file:
      - .env
    #    links:
    #      - postgres
    depends_on:
      - postgres
    image: koryto_web
    ports:
      - "8080:8080"

volumes:
  pgdata:
    driver: local
