INSERT INTO parts (part_name, category_id, manufacturer_id, car_id, part_description) VALUES
('Timing Belt', 1, 1, 1, 'Synchronizes engine components for efficient performance'),
('Battery', 2, 2, 1, 'Reliable battery for long-lasting power'),
('Brake Caliper', 4, 3, 2, 'High-quality caliper for consistent braking'),
('Fuel Injector', 1, 2, 2, 'Enhances fuel delivery for better combustion'),
('Headlight Bulb', 2, 1, 3, 'Bright and efficient headlight replacement'),
('Wheel Bearing', 3, 3, 3, 'Reduces friction for smooth wheel rotation'),
('Oxygen Sensor', 5, 2, 4, 'Monitors exhaust gases for better fuel efficiency'),
('Radiator', 1, 1, 4, 'Keeps engine cool for optimal performance'),
('Tailpipe', 5, 3, 5, 'Durable and corrosion-resistant tailpipe'),
('Strut Mount', 3, 2, 5, 'Provides stability and reduces vibrations'),
('Ignition Coil', 2, 1, 6, 'Delivers high voltage to spark plugs'),
('Fuel Pump', 1, 2, 6, 'Ensures steady fuel flow to the engine'),
('Control Arm', 3, 3, 7, 'Supports suspension and improves handling'),
('ABS Sensor', 4, 2, 7, 'Monitors wheel speed for safe braking'),
('Turbocharger', 1, 1, 8, 'Boosts engine power and efficiency'),
('EGR Valve', 5, 2, 8, 'Reduces nitrogen oxide emissions'),
('Rearview Mirror', 2, 3, 9, 'Provides a clear rearward view'),
('Brake Hose', 4, 2, 9, 'Transmits hydraulic pressure to the brakes'),
('Leaf Spring', 3, 1, 10, 'Supports load and absorbs shock'),
('Clutch Disc', 1, 2, 10, 'Provides smooth engagement and power transfer');
