spring:
  application:
    name: koryto

logging:
  level:
    cat.mood.koryto: DEBUG
    org:
      springframework:
        web: debug
        security: debug
cat:
  mood:
    koryto:
      host: ${DB_HOST}
      name: ${DB_NAME}
      user: ${DB_USER}
      password: ${DB_PASSWORD}
      port: ${DB_PORT}

