spring:
  application:
    name: koryto

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %highlight(%-5level) [%thread] %logger{36} - %msg%n'
  level:
    cat.mood.koryto: DEBUG
    org:
      springframework:
        web: debug
        security: debug
cat:
  mood:
    koryto:
      datasource:
        host: ${DB_HOST}
        name: ${DB_NAME}
        admin: ${DB_USER}
        adminPassword: ${DB_PASSWORD}
        port: ${DB_PORT}
        maxPoolSize: 10
        user: regular_user
        userPassword: regular_password
      redis:
        host: ${REDIS_HOST}
        port: ${REDIS_PORT}
        password: ${REDIS_PASSWORD}
